# IRIS FLOWER CLASSIFICATION


In [89]:
import pandas as pd
import numpy as np
df=pd.read_csv("iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [90]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [92]:
dt=df.drop('Species',axis=1)
corr1=dt.corr()
print(corr1)

                     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Id             1.000000       0.716676     -0.397729       0.882747   
SepalLengthCm  0.716676       1.000000     -0.109369       0.871754   
SepalWidthCm  -0.397729      -0.109369      1.000000      -0.420516   
PetalLengthCm  0.882747       0.871754     -0.420516       1.000000   
PetalWidthCm   0.899759       0.817954     -0.356544       0.962757   

               PetalWidthCm  
Id                 0.899759  
SepalLengthCm      0.817954  
SepalWidthCm      -0.356544  
PetalLengthCm      0.962757  
PetalWidthCm       1.000000  


In [93]:
from sklearn.model_selection import train_test_split
X=df.drop('Id',axis=1)
X=X.drop('Species',axis=1)
y=df['Species']

In [94]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

# logistic regression


In [96]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
model=LogisticRegression(solver='lbfgs',max_iter=700)
model.fit(x_train,y_train)
predict1=model.predict(x_test)


In [97]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_mat1=confusion_matrix(y_test,predict1)
print("confusion matrix:\n",confusion_mat1)

confusion matrix:
 [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [98]:
print("\nClassification Report:")
print(classification_report(y_test, predict1))


Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      0.94      0.97        16
 Iris-virginica       0.90      1.00      0.95         9

       accuracy                           0.97        38
      macro avg       0.97      0.98      0.97        38
   weighted avg       0.98      0.97      0.97        38



In [99]:
print('Accuracy:',metrics.accuracy_score(predict1,y_test))

Accuracy: 0.9736842105263158


In [106]:
x_new = np.array([ [4.9, 2.2, 3.8, 1.1 ],[ 5.3, 2.5, 4.6, 1.9 ],[3, 2, 1, 0.2]])
predict2 = model.predict(x_new)
print("Prediction of Species:",predict2)

Prediction of Species: ['Iris-versicolor' 'Iris-virginica' 'Iris-setosa']


C:\Users\admin\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
